version: '3.8'

services:
  db:
    container_name: MainDatabase
    build: ./mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PWD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "$DB_PORT:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    container_name: AdminWebsite
    depends_on:
      - db
    image: phpmyadmin:5.2.1-apache
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "$ADMIN_PORT:80"
    environment:
      PMA_HOST: db
  app:
    container_name: AppServer
    depends_on:
      - db
    build: ./src
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$APP_PORT:3000"
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PWD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PWD=$EMAIL_PWD

volumes:
  db_data:
